name: generate issue tracking and std lib docs and deploy them to github pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: checkout main branch
        uses: actions/checkout@v4
        with:
          path: ./main-branch

      - name: fetch gh-pages branch for the historical data
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: ./gh-pages
          continue-on-error: true

      - name: generate new state and prepare for deploy
        run: |
            # copy the state from gh-pages branch into the main-branch checkout
            mkdir -p ./main-branch/.github/scripts/.issues/state
            cp -r gh-pages/state ./main-branch/.github/scripts/.issues &2>/dev/null || true

            pushd main-branch/.github/scripts/

            pip install -r requirements.txt
            python track_issues.py

            popd

            cp -r ./main-branch/.github/scripts/.issues/ ./.issues

      - name: generate new docs_output.html from std/std.duck and prepare for deploy
        run: |
            pushd main-branch
            chmod +x install_std.sh
            ./install_std.sh

            pushd std

            cargo run docs std.duck

            popd
            popd

            cp ./main-branch/std/docs_output.html ./.issues/docs_output.html

      - name: deploy to github actions
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.issues
          publish_branch: gh-pages
          force_orphan: false
          commit_message: "docs: generate std docs and track issues [skip ci]"
