name: generate std docs

on:
  push:
  workflow_dispatch:

jobs:
  generate-docs-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: generate new docs_output.html from std/std.duck and prepare for deploy
        run: |
            chmod +x install_std.sh
            ./install_std.sh

            pushd std

            cargo run docs std.duck

            popd

            mkdir docs_html
            cp std/docs_output.html docs_html/docs_output.html

      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs_html
          publish_branch: gh-pages
          force_orphan: false
          commit_message: "docs: generate std docs [skip ci]"
