name: cargo test and python test scripts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  run_cargo_tests:
    name: run 'cargo test'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - run: cargo test
  run_python_tests:
    name: run python test scripts against compiler
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: setup rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: run python test script in cicd and release mode
      run: |
        ./install_std.sh
        cd ./tests
        export RUST_BACKTRACE=0
        python run_tests.py --cicd --release
